# Generated by Django 5.1.7 on 2025-03-25 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ho_ten', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChiNhanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_chi_nhanh', models.CharField(max_length=100)),
                ('dia_chi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Phim',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tieu_de', models.CharField(max_length=100)),
                ('the_loai', models.CharField(max_length=50)),
                ('thoi_luong', models.IntegerField()),
                ('ngay_phat_hanh', models.DateField()),
                ('anh_phim', models.ImageField(upload_to='phim/')),
                ('dao_dien', models.CharField(max_length=100)),
                ('is_now_showing', models.BooleanField(default=False)),
                ('coming_soon', models.BooleanField(default=False)),
                ('tomtatphim', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RapChieu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_rap', models.CharField(max_length=100)),
                ('dia_chi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_danh_gia', models.PositiveSmallIntegerField()),
                ('binh_luan', models.TextField()),
                ('ngay_danh_gia', models.DateTimeField(auto_now_add=True)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('phim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinego.phim')),
            ],
        ),
        migrations.CreateModel(
            name='QuanTriVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LichChieu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ngay_chieu', models.DateField()),
                ('gio_chieu', models.TimeField()),
                ('phim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinego.phim')),
                ('rap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinego.rapchieu')),
            ],
        ),
        migrations.CreateModel(
            name='Ve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_ghe', models.IntegerField()),
                ('gia_ve', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lich_chieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinego.lichchieu')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
